import Script from "next/script";
import Header from "./components/header";
import Footer from "./components/footer";
import "../(blog)/../../style/globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Script
        id="adsbygoogle-init"
        strategy="afterInteractive"
        crossOrigin="anonymous"
        src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1436861775123746"
      />
      <Script
        id="googleanalyticsurl"
        async
        src="https://www.googletagmanager.com/gtag/js?id=G-6RDMHPJ0C0"
      ></Script>
      <Script id="googleanalyticsscript">
        {` window.dataLayer = window.dataLayer || []; function gtag()
        {dataLayer.push(arguments)}
        gtag('js', new Date()); gtag('config', 'G-6RDMHPJ0C0');`}
      </Script>
      <body className="bg-slate-100">
        <Header />

        {children}
        <Footer />
      </body>
    </html>
  );
}
